apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-app-mjqi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-app-mjqi
    app.kubernetes.io/part-of: my-app
  name: demo-app-mjqi
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo-app-mjqi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: demo-app-mjqi
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:3be090458a78bd427d809fa1d3f747a2125fee5ac8c2c4e2e27e671002057bbc
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3000
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
